version: "3.7"

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: curl --fail http://localhost:80/healthy || exit 1
      interval: 2s
      timeout: 2s
      retries: 5
    depends_on:
      server:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      SQL_USER: ${POSTGRES_USER}
      SQL_PASSWORD: ${POSTGRES_PASSWORD}
      SQL_DB: ${POSTGRES_DB}
      SQL_HOST: "postgresql:5432"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    healthcheck:
      test: curl --fail http://localhost:80/api/healthy || exit 1
      interval: 2s
      timeout: 2s
      retries: 5
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 2s
      timeout: 2s
      retries: 5



volumes:
  postgresql:
