name: server

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  merge_group:
    branches: [ main ]

jobs:
  server-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.local/share/pypoetry/
            server/target/
          key: ${{ runner.os }}-python-${{ hashFiles('server/poetry.lock') }}
          restore-keys: ${{ runner.os }}-python-

      - name: Install poetry & dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry --version
          poetry install -vv -C ./server -n

      - name: Black formatting check
        run: |
          poetry run -C ./server black --check --verbose ./server

      - name: Pylint check
        run: |
          poetry run -C ./server pylint $(git ls-files './server/**/*.py')
